import Head from 'next/head'
import {NextPage} from "next";
import {useRouter} from "next/router";
import {paths} from "@/core/paths";
import {useEffect} from "react";


const HomePage: NextPage = () => {
    const router = useRouter()
    
    useEffect(() => {
        router.push(paths.pages.dashboard)
    }, [])
    
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            
            <main>
            
            </main>
        </>
    )
}

export default HomePage